require 'jar_dependencies'
JBUNDLER_LOCAL_REPO = Jars.home
JBUNDLER_JRUBY_CLASSPATH = []
JBUNDLER_JRUBY_CLASSPATH.freeze
JBUNDLER_TEST_CLASSPATH = []
JBUNDLER_TEST_CLASSPATH.freeze
JBUNDLER_CLASSPATH = []
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/hadoop/hadoop-auth/2.6.5/hadoop-auth-2.6.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/curator/curator-framework/2.6.0/curator-framework-2.6.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/hadoop/hadoop-yarn-client/2.6.5/hadoop-yarn-client-2.6.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/directory/api/api-asn1-api/1.0.0-M20/api-asn1-api-1.0.0-M20.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/codehaus/jackson/jackson-jaxrs/1.9.13/jackson-jaxrs-1.9.13.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/directory/api/api-util/1.0.0-M20/api-util-1.0.0-M20.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/tukaani/xz/1.0/xz-1.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-lang/commons-lang/2.6/commons-lang-2.6.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/httpcomponents/httpcore/4.2.4/httpcore-4.2.4.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/hadoop/hadoop-mapreduce-client-core/2.6.5/hadoop-mapreduce-client-core-2.6.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/xml-apis/xml-apis/1.3.04/xml-apis-1.3.04.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/sun/jersey/jersey-core/1.9/jersey-core-1.9.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/fusesource/leveldbjni/leveldbjni-all/1.8/leveldbjni-all-1.8.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/hadoop/hadoop-hdfs/2.6.5/hadoop-hdfs-2.6.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/mortbay/jetty/jetty-util/6.1.26/jetty-util-6.1.26.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/log4j/log4j/1.2.17/log4j-1.2.17.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/google/guava/guava/11.0.2/guava-11.0.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/hadoop/hadoop-mapreduce-client-jobclient/2.6.5/hadoop-mapreduce-client-jobclient-2.6.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/io/netty/netty/3.6.2.Final/netty-3.6.2.Final.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/hadoop/hadoop-common/2.6.5/hadoop-common-2.6.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-digester/commons-digester/1.8/commons-digester-1.8.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/javax/activation/activation/1.1/activation-1.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/thoughtworks/paranamer/paranamer/2.3/paranamer-2.3.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/httpcomponents/httpclient/4.2.5/httpclient-4.2.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/xmlenc/xmlenc/0.52/xmlenc-0.52.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/hadoop/hadoop-yarn-common/2.6.5/hadoop-yarn-common-2.6.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/hadoop/hadoop-mapreduce-client-app/2.6.5/hadoop-mapreduce-client-app-2.6.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-beanutils/commons-beanutils-core/1.8.0/commons-beanutils-core-1.8.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-cli/commons-cli/1.2/commons-cli-1.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/zookeeper/zookeeper/3.4.6/zookeeper-3.4.6.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/avro/avro/1.7.4/avro-1.7.4.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/commons/commons-compress/1.4.1/commons-compress-1.4.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/curator/curator-client/2.6.0/curator-client-2.6.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/javax/servlet/servlet-api/2.5/servlet-api-2.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/yaml/snakeyaml/1.14/snakeyaml-1.14.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-codec/commons-codec/1.4/commons-codec-1.4.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/codehaus/jackson/jackson-xc/1.9.13/jackson-xc-1.9.13.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/xerces/xercesImpl/2.9.1/xercesImpl-2.9.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/sun/jersey/jersey-client/1.9/jersey-client-1.9.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/commons/commons-math3/3.1.1/commons-math3-3.1.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/hadoop/hadoop-annotations/2.6.5/hadoop-annotations-2.6.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/hadoop/hadoop-yarn-server-common/2.6.5/hadoop-yarn-server-common-2.6.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/hadoop/hadoop-client/2.6.5/hadoop-client-2.6.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-io/commons-io/2.4/commons-io-2.4.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/curator/curator-recipes/2.6.0/curator-recipes-2.6.0.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/hadoop/hadoop-yarn-api/2.6.5/hadoop-yarn-api-2.6.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/hadoop/hadoop-mapreduce-client-shuffle/2.6.5/hadoop-mapreduce-client-shuffle-2.6.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/htrace/htrace-core/3.0.4/htrace-core-3.0.4.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-net/commons-net/3.1/commons-net-3.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/xerial/snappy/snappy-java/1.0.4.1/snappy-java-1.0.4.1.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/org/apache/hadoop/hadoop-mapreduce-client-common/2.6.5/hadoop-mapreduce-client-common-2.6.5.jar')
JBUNDLER_CLASSPATH << (JBUNDLER_LOCAL_REPO + '/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar')
JBUNDLER_CLASSPATH.freeze
